apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - name : msvc-cursos
          image: lucho2024/docker-micros-msvc-cursos:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: 8002
            - name: DB_HOST
              value: "mysql8:3306"